version: '3.9'
services:
  web:
    image: nginx:alpine
    ports:
      - "32804:80"
    volumes:
      - ./src/:/usr/share/nginx/html:ro
    working_dir: /usr/share/nginx/html
    restart: unless-stopped
