sonar.projectKey=importHolidaysIntoEasyAppointments

# Verzeichnisse ausschließen
sonar.exclusions=**/.idea/**

# Mehrere Verzeichnisse ausschließen
# sonar.exclusions=**/.idea/**,**/node_modules/**,**/dist/**
